### ISSUE TITLE
bug: no mention of SQL in README & inability to use without SQL

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-api#116]
This project needs an SQL Server to run, there's no setup instructions or mention of the usage, it should also be possible to disable as it ultimately makes it difficult to contribute

**Comment by alexandreteles** [comment]
Because it doesn't require a server. It uses sqlite which is file based.

**Comment by Ushie** [comment]
What am I supposed to do to allow it to use the file it needs? I can't run the project and there's no instructions on what to do:

```
Traceback (most recent call last):
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/bin/sanic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/__main__.py", line 12, in main
    cli.run(args)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/cli/app.py", line 106, in run
    app = self._get_app(app_loader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/cli/app.py", line 175, in _get_app
    app = app_loader.load()
          ^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/worker/loader.py", line 78, in load
    module = import_module(self.module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ushie/git/revanced-api/app.py", line 6, in <module>
    from api import api
  File "/home/ushie/git/revanced-api/api/__init__.py", line 10, in <module>
    from api.announcements import announcements
  File "/home/ushie/git/revanced-api/api/announcements.py", line 18, in <module>
    from data.models import AnnouncementDbModel, AttachmentDbModel
  File "/home/ushie/git/revanced-api/data/models.py", line 77, in <module>
    Base.metadata.create_all(engine)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 5828, in create_all
    bind._run_ddl_visitor(
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3242, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3232, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by oSumAtrIX** [comment]
It failed to open the db. Does the path exist?

**Comment by oSumAtrIX** [comment]
In any case, SQLite is used, so no server is needed.

**Comment by Ushie** [comment]
What path? you need to document the necessary path for me to create.

**Comment by oSumAtrIX** [comment]
The path should be present already: https://github.com/ReVanced/revanced-api/tree/main/persistance

The READMEs installation instructions should be enough to setup and run the server.

**Comment by Ushie** [comment]
In that case, yes that path exists in my side and no I'm unable to run the server, logs above are the printed logs

**Comment by Ushie** [comment]
Have you tested it outside of a Docker environment?

**Comment by oSumAtrIX** [comment]
Yes, I'll try again.

**Comment by oSumAtrIX** [comment]
It should be fixed with https://github.com/ReVanced/revanced-api/commit/500a5896e34f6a9600dcec2834b3d340161bb90a. There was a typo in the path.

**Comment by Ushie** [comment]
I get this now:
```
Traceback (most recent call last):
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/bin/sanic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/__main__.py", line 12, in main
    cli.run(args)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/cli/app.py", line 106, in run
    app = self._get_app(app_loader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/cli/app.py", line 175, in _get_app
    app = app_loader.load()
          ^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/worker/loader.py", line 78, in load
    module = import_module(self.module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ushie/git/revanced-api/app.py", line 32, in <module>
    configure_auth(app)
  File "/home/ushie/git/revanced-api/auth.py", line 14, in configure_auth
    app.config.SECRET_KEY = os.environ.get("SECRET_KEY").join(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'join'
ushie@DESKTOP-734HT60:~/git/revanced-api$ poetry run sanic app:app --dev
Traceback (most recent call last):
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/bin/sanic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/__main__.py", line 12, in main
    cli.run(args)
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/cli/app.py", line 106, in run
    app = self._get_app(app_loader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/cli/app.py", line 175, in _get_app
    app = app_loader.load()
          ^^^^^^^^^^^^^^^^^
  File "/home/ushie/.cache/pypoetry/virtualenvs/revanced-api-1kDCPdcC-py3.11/lib/python3.11/site-packages/sanic/worker/loader.py", line 78, in load
    module = import_module(self.module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ushie/git/revanced-api/app.py", line 32, in <module>
    configure_auth(app)
  File "/home/ushie/git/revanced-api/auth.py", line 14, in configure_auth
    app.config.SECRET_KEY = os.environ.get("SECRET_KEY").join(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'join'
```

Relevant LoCs: 
```py
def configure_auth(app):
    app.config.SECRET_KEY = os.environ.get("SECRET_KEY").join(
        secrets.choice(string.ascii_letters) for i in range(15)
    )
    app.config["TOKEN_ACCESS_LIFESPAN"] = {"hours": 24}
    app.config["TOKEN_REFRESH_LIFESPAN"] = {"days": 30}
    beskar.init_app(app, UserDbModel)

    _init_default_user()```

**Comment by oSumAtrIX** [comment]
You are missing the env variables as specified in the usage: https://github.com/ReVanced/revanced-api?tab=readme-ov-file#usage

**Comment by Ushie** [comment]
I updated my message

**Comment by oSumAtrIX** [comment]
The process you start the interpreter with does not pick up the env variables, try exporting them.
