### ISSUE TITLE
bug: `v3/patches/list` endpoint broken

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-api#189]
### Bug description

The patches/list endpoint was likely broken by this commit https://github.com/ReVanced/revanced-api/commit/e113daa089e21079de06e12b05a140c1af57a527

### Error logs

```shell
2024-09-07 21:28:08.583 [ktor-jetty-8888-3] ERROR ktor.application - Unhandled: GET - /v3/patches/list
java.lang.IncompatibleClassChangeError: class app.revanced.patches.moneymanager.UnlockProPatch cannot inherit from final class app.revanced.patcher.patch.BytecodePatch
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at app.revanced.patcher.patch.PatchLoader$Companion.loadPatches$lambda$7$lambda$4(Patch.kt:666)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:329)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:318)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:842)
	at app.revanced.patcher.patch.PatchLoader$Companion.loadPatches(Patch.kt:671)
	at app.revanced.patcher.patch.PatchLoader$Companion.access$loadPatches(Patch.kt:631)
	at app.revanced.patcher.patch.PatchLoader.<init>(Patch.kt:585)
	at app.revanced.patcher.patch.PatchLoader.<init>(Patch.kt)
	at app.revanced.patcher.patch.PatchLoader$Jar.<init>(Patch.kt:595)
	at app.revanced.patcher.patch.PatchKt.loadPatchesFromJar(Patch.kt:686)
	at app.revanced.api.configuration.services.PatchesService$list$2.invokeSuspend$lambda$3(PatchesService.kt:97)
	at app.revanced.api.configuration.services.PatchesService$list$2.invokeSuspend$lambda$4(PatchesService.kt:78)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at app.revanced.api.configuration.services.PatchesService$list$2.invokeSuspend(PatchesService.kt:78)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

### Solution

Don't use dev release of ReVanced Library

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Oh that makes sense. I think the reason lib was bumped was to fix another issue which is  the option objects not to be keyed by the option name. The deployment will be rolled back to the last release with patcher v19 but updates will not be possible until everything has switched to v20 (manager is needed only)

**Comment by oSumAtrIX** [comment]
I've reverted the deployment to v1.1.0
